name: filcnaplo_desktop_ui
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_feather_icons: ^2.0.0+1
  
flutter:
  uses-material-design: true